// <auto-generated />
namespace LessonPlanner_DataLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class LessonTable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(LessonTable));
        
        string IMigrationMetadata.Id
        {
            get { return "202006291448597_LessonTable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
